default_stages:
  - pre-commit

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        name: check conventional commit
        stages: [commit-msg]
        args: [fix, feat, test, ci, chore, wip]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude_types:
          - "markdown"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: detect hardcoded secrets
