name: "Calendar Versioning"
description: "Simple CalVer GitHub Composite Action."
author: "jterral"

branding:
  icon: "tag"
  color: "green"

inputs:
  tag-prefix:
    description: "Optional prefix for the tag (e.g., 'api-'). Default: empty."
    required: false
    default: ""

  tag-push:
    description: "If true, the tag will be pushed to the remote repository."
    required: false
    default: "false"

  commit-email:
    description: "Email used for the git tag commit."
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

  commit-name:
    description: "Name used for the git tag commit."
    required: false
    default: "github-actions[bot]"

outputs:
  tag:
    description: "Generated tag (e.g., 25.32.0 or api-25.32.0)."
    value: ${{ steps.generate-tag.outputs.tag }}

  version:
    description: "Generated version with build number (e.g., 25.32.0+1234)."
    value: ${{ steps.generate-tag.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: generate-tag
      shell: bash
      env:
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "::group::🔖 Versioning"

        calver=$(date +'%y.%U')
        minor=$(git tag -l "${INPUT_TAG_PREFIX}${calver}.*" | sort -V | wc -l)
        tag="${INPUT_TAG_PREFIX}${calver}.${minor}"
        version="${tag}+${GITHUB_RUN_NUMBER}"

        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        echo "version=$version" >> "$GITHUB_OUTPUT"

        echo "Generated tag: $tag"
        echo "Generated version: $version"

        echo "::endgroup::"

    - id: push-tag
      shell: bash
      env:
        INPUT_COMMIT_EMAIL: ${{ inputs.commit-email }}
        INPUT_COMMIT_NAME: ${{ inputs.commit-name }}
        INPUT_PUSH_TAG: ${{ inputs.tag-push }}
        TAG: ${{ steps.generate-tag.outputs.tag }}
        VERSION: ${{ steps.generate-tag.outputs.version }}
      run: |
        echo "::group::🔧 Git Config"
        git config --global user.email "${INPUT_COMMIT_EMAIL}"
        git config --global user.name "${INPUT_COMMIT_NAME}"
        echo "Configured git as ${INPUT_COMMIT_NAME} <${INPUT_COMMIT_EMAIL}>"
        echo "::endgroup::"

        echo "::group::🏷️ Tagging"
        git tag -a "$TAG" -m "$VERSION"
        echo "Created tag: $TAG"
        echo "::endgroup::"

        if [[ "$INPUT_PUSH_TAG" == "true" ]]; then
          echo "::group::🚀 Pushing tag"
          git push origin "$TAG" || {
            echo "::error::❌ Failed to push tag '$TAG'. Check your PAT permissions."
            exit 1
          }
          echo "✅ Tag $TAG pushed to origin"
          echo "::endgroup::"
        else
          echo "🧪 Skipping tag push (tag-push=false)"
        fi
