name: "Calendar Versioning"
description: "Simple CalVer GitHub Composite Action."

inputs:
  tag-prefix:
    description: "Optional prefix for the tag. Example: 'api-'. Default: empty"
    required: false
    default: ""

  tag-push:
    description: "Whether to push the tag to the remote. Default: false"
    required: false
    default: "false"

  commit-email:
    description: "Git commit email. Default: github-actions[bot]@users.noreply.github.com"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

  commit-name:
    description: "Git commit name. Default: github-actions[bot]"
    required: false
    default: "github-actions[bot]"

outputs:
  tag:
    description: "The generated tag (e.g., 25.32.0 or api-25.32.0)"
    value: ${{ steps.calver.outputs.tag }}

  version:
    description: "The generated version with build number (e.g., 25.32.0+1234)"
    value: ${{ steps.calver.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate tag and version
      id: calver
      shell: bash
      run: ./scripts/generate-version.sh
      env:
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}

    - name: Push tag (if tag-push is true)
      shell: bash
      run: ./scripts/push-tag.sh
      env:
        INPUT_COMMIT_EMAIL: ${{ inputs.commit-email }}
        INPUT_COMMIT_NAME: ${{ inputs.commit-name }}
        INPUT_PUSH_TAG: ${{ inputs.tag-push }}
        TAG: ${{ steps.calver.outputs.tag }}
        VERSION: ${{ steps.calver.outputs.version }}
