name: "Calendar Versioning"
description: "Simple CalVer GitHub Composite Action."

inputs:
  tag-prefix:
    description: "Optional prefix for the tag. Example: 'api-'. Default: empty"
    required: false
    default: ""

  tag-push:
    description: "Whether to push the tag to the remote. Default: false"
    required: false
    default: "false"

  commit-email:
    description: "Git commit email. Default: github-actions[bot]@users.noreply.github.com"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

  commit-name:
    description: "Git commit name. Default: github-actions[bot]"
    required: false
    default: "github-actions[bot]"

outputs:
  tag:
    description: "The generated tag (e.g., 25.32.0 or api-25.32.0)"
    value: ${{ steps.generate-tag.outputs.tag }}

  version:
    description: "The generated version with build number (e.g., 25.32.0+1234)"
    value: ${{ steps.generate-tag.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: generate-tag
      shell: bash
      env:
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "::group::🔖 Versioning"

        calver=$(date +'%y.%U')
        minor=$(git tag -l "$calver.*" | sort -V | wc -l)
        tag="${INPUT_TAG_PREFIX}${calver}.${minor}"
        version="${tag}+${GITHUB_RUN_NUMBER}"

        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT

        echo "Generated tag: $tag"
        echo "Generated version: $version"

        echo "::endgroup::"

    - id: push-tag
      shell: bash
      run: scripts/push-tag.sh
      env:
        INPUT_COMMIT_EMAIL: ${{ inputs.commit-email }}
        INPUT_COMMIT_NAME: ${{ inputs.commit-name }}
        INPUT_PUSH_TAG: ${{ inputs.tag-push }}
        TAG: ${{ steps.generate-tag.outputs.tag }}
        VERSION: ${{ steps.generate-tag.outputs.version }}
      run: |
        echo "::group::🔧 Git Config"
        git config --global user.email "${INPUT_COMMIT_EMAIL}"
        echo "Configured git user email: ${INPUT_COMMIT_EMAIL}"
        git config --global user.name "${INPUT_COMMIT_NAME}"
        echo "Configured git user name: ${INPUT_COMMIT_NAME}"
        echo "::endgroup::"

        echo "::group::🏷️ Tagging"
        git tag -a "$TAG" -m "$VERSION"
        echo "Created tag $TAG"
        echo "::endgroup::"

        if [[ "$INPUT_PUSH_TAG" == "true" ]]; then
          echo "::group::🚀 Pushing tag"
          git push origin "$TAG" || {
            echo "::error::❌ Failed to push tag '$TAG'. Check permissions or token scope."
            exit 1
          }
          echo "✅ Tag $TAG pushed to origin"
          echo "::endgroup::"
        else
          echo "🧪 push-tag=false → skipping push of $TAG"
        fi
